### ISSUE TITLE
Not downloading specific Webtoon

### ISSUE THREAD

**Issue by qunYp3dZSyLjoEoEg** [Zehina/Webtoon-Downloader#10]
Hello,
I tried to download the prettiest platypus with this program, however, it didn't work. This is the link I used(https://www.webtoons.com/en/challenge/the-prettiest-platypus/chapter-1-the-new-cat-in-town/viewer?title_no=463063&episode_no=2). 
I do see that it is a little bit different than the one in the example, however, I do not have an idea how to correct it if that is the problem. 
My OS is Linux(Arch-based) with python 3.10.4, the error message when executing this(python webtoon_downloader.py "https://www.webtoons.com/en/challenge/the-prettiest-platypus/chapter-1-the-new-cat-in-town/list?title_no=463063&episode_no=2") command I get is : 
Traceback (most recent call last):
  File "/home/username/Documents/Webtoon-Downloader/src/webtoon_downloader.py", line 438, in <module>
    main()
  File "/home/username/Documents/Webtoon-Downloader/src/webtoon_downloader.py", line 435, in main
    download_webtoon(series_url, args.start, args.end, args.dest, args.images_format, args.latest, separate)
  File "/home/username/Documents/Webtoon-Downloader/src/webtoon_downloader.py", line 358, in download_webtoon
    viewer_url = get_chapter_viewer_url(soup)
  File "/home/username/Documents/Webtoon-Downloader/src/webtoon_downloader.py", line 165, in get_chapter_viewer_url
    return html.find('li', attrs={'data-episode-no': True}).find('a')['href'].split('&')[0]
AttributeError: 'NoneType' object has no attribute 'find
.

Any help would be appreciated. Sorry if this is the wrong tab in github for this kind of issue, I'm pretty new to this. Many thanks in advance.

**Comment by qunYp3dZSyLjoEoEg** [comment]
Nvm I just found out I had to use the link from the actual comic where I can choose which chapter to read and not one from a specific chapter. Might still be a nice addition to be able to give it the link to a specific chapter and to then have it download only that, only onwards from that etc.
