### ISSUE TITLE
Can't download specific webtoon(for real)

### ISSUE THREAD

**Issue by qunYp3dZSyLjoEoEg** [Zehina/Webtoon-Downloader#12]
Hello, 
I can't download this https://www.webtoons.com/en/challenge/serious-trans-vibes/list?title_no=206579 webtoon Haven't encountered that problem with any other webtoon. Here's the error message: 
wtdl https://www.webtoons.com/en/challenge/serious-trans-vibes/list?title_no=206579
[08:20:04] WARNING  Directory Exists: /home/username/Documents/Webtoon-Downloader/            webtoon_downloader.py:366
Downloading Serious Trans Vibes from https://www.webtoons.com/en/challenge/serious-trans-vibes/list?title_no=206579

Traceback (most recent call last):
  File "/home/username/Documents/Webtoons/Webtoon-Downloader/src/webtoon_downloader.py", line 438, in <module>
    main()
  File "/home/username/Documents/Webtoons/Webtoon-Downloader/src/webtoon_downloader.py", line 435, in main
    download_webtoon(series_url, args.start, args.end, args.dest, args.images_format, args.latest, separate)
  File "/home/username/Documents/Webtoons/Webtoon-Downloader/src/webtoon_downloader.py", line 374, in download_webtoon
    chapters_to_download = get_chapters_details(session, viewer_url, start_chapter, end_chapter)
  File "/home/username/Documents/Webtoons/Webtoon-Downloader/src/webtoon_downloader.py", line 203, in get_chapters_details
    in enumerate(soup.find('div', class_='episode_cont').find_all('li'), start=1)]
AttributeError: 'NoneType' object has no attribute 'find_all'
. Sorry if it's something easy/obvious. Thanks in advance.

**Comment by qunYp3dZSyLjoEoEg** [comment]
This 
alias wtdl="python ~/Documents/Webtoons/Webtoon-Downloader/src/webtoon_downloader.py --dest /home/username/Documents/Webtoon-Downloader/"

is the alias for wtdl, it just calls it and loads the images into another folder.

**Comment by Zehina** [comment]
This should be fixed in 87791a8217924066d8cc53033ac8107073f8fbea with a very bad temporary solution. Since I have no time. But test it and let me know. It should work now

**Comment by qunYp3dZSyLjoEoEg** [comment]
Worked like a charm, thank you!
